// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: js/javascript_package.proto

/**
 * @fileoverview Generated Protocol Buffer code for file js/javascript_package.proto.
 */


goog.require('goog.proto2.Message');

goog.require('google.protobuf.FileDescriptorSet');
goog.require('google.protobuf.FileDescriptorProto');
goog.require('google.protobuf.DescriptorProto');
goog.require('google.protobuf.FieldDescriptorProto');
goog.require('google.protobuf.EnumDescriptorProto');
goog.require('google.protobuf.EnumValueDescriptorProto');
goog.require('google.protobuf.ServiceDescriptorProto');
goog.require('google.protobuf.MethodDescriptorProto');
goog.require('google.protobuf.FileOptions');
goog.require('google.protobuf.MessageOptions');
goog.require('google.protobuf.FieldOptions');
goog.require('google.protobuf.EnumOptions');
goog.require('google.protobuf.EnumValueOptions');
goog.require('google.protobuf.ServiceOptions');
goog.require('google.protobuf.MethodOptions');
goog.require('google.protobuf.UninterpretedOption');
goog.require('google.protobuf.SourceCodeInfo');


