var l=void 0,p=!0,q=null,r=!1,v=this;
function w(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function y(a){return"string"==typeof a}function z(a){return a[aa]||(a[aa]=++ba)}var aa="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ba=0;function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function ea(a,b,c){ea=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return ea.apply(q,arguments)}
function fa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}function A(a,b){var c=a.split("."),d=v;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==l?d[e]=b:d=d[e]?d[e]:d[e]={}}function ga(a,b){function c(){}c.prototype=b.prototype;a.T=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ha(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};var B,ia,ja,ka;function la(){return v.navigator?v.navigator.userAgent:q}ka=ja=ia=B=r;var ma;if(ma=la()){var na=v.navigator;B=0==ma.indexOf("Opera");ia=!B&&-1!=ma.indexOf("MSIE");ja=!B&&-1!=ma.indexOf("WebKit");ka=!B&&!ja&&"Gecko"==na.product}var C=B,D=ia,E=ka,F=ja;function oa(){var a=v.document;return a?a.documentMode:l}var pa;
a:{var qa="",ra;if(C&&v.opera)var sa=v.opera.version,qa="function"==typeof sa?sa():sa;else if(E?ra=/rv\:([^\);]+)(\)|;)/:D?ra=/MSIE\s+([^\);]+)(\)|;)/:F&&(ra=/WebKit\/(\S+)/),ra)var ta=ra.exec(la()),qa=ta?ta[1]:"";if(D){var ua=oa();if(ua>parseFloat(qa)){pa=String(ua);break a}}pa=qa}var va={};
function G(a){var b;if(!(b=va[a])){b=0;for(var c=ha(String(pa)).split("."),d=ha(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"",j=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var k=j.exec(g)||["","",""],t=m.exec(h)||["","",""];if(0==k[0].length&&0==t[0].length)break;b=((0==k[1].length?0:parseInt(k[1],10))<(0==t[1].length?0:parseInt(t[1],10))?-1:(0==k[1].length?0:parseInt(k[1],10))>(0==t[1].length?0:parseInt(t[1],10))?1:0)||((0==k[2].length)<
(0==t[2].length)?-1:(0==k[2].length)>(0==t[2].length)?1:0)||(k[2]<t[2]?-1:k[2]>t[2]?1:0)}while(0==b)}b=va[a]=0<=b}return b}var wa=v.document,xa=!wa||!D?l:oa()||("CSS1Compat"==wa.compatMode?parseInt(pa,10):5);var ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function za(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<ya.length;f++)c=ya[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Aa=Array.prototype,Ba=Aa.indexOf?function(a,b,c){return Aa.indexOf.call(a,b,c)}:function(a,b,c){c=c==q?0:0>c?Math.max(0,a.length+c):c;if(y(a))return!y(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},H=Aa.forEach?function(a,b,c){Aa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=y(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};function Ca(a,b){0<=Ba(a,b)||a.push(b)};function I(a,b){this.x=a!==l?a:0;this.y=b!==l?b:0}I.prototype.a=function(){return new I(this.x,this.y)};I.prototype.toString=function(){return"("+this.x+", "+this.y+")"};I.prototype.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};I.prototype.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function J(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}J.prototype.a=function(){return new J(this.top,this.right,this.bottom,this.left)};J.prototype.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};J.prototype.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
J.prototype.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function K(a,b){this.width=a;this.height=b}K.prototype.a=function(){return new K(this.width,this.height)};K.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};K.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};K.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Da;function Ea(a){var b=Fa;a=a.className;a=y(a)&&a.match(/\S+/g)||[];return 0<=Ba(a,b)};!E&&!D||D&&D&&9<=xa||E&&G("1.9.1");D&&G("9");function Ga(a){return a?new Ha(Ia(a)):Da||(Da=new Ha)}function Ja(a){return y(a)?document.getElementById(a):a}function Ka(a){a=a.document;a="CSS1Compat"==a.compatMode?a.documentElement:a.body;return new K(a.clientWidth,a.clientHeight)}function La(a){return a.previousElementSibling!=l?a.previousElementSibling:Ma(a.previousSibling,r)}function Ma(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function Ia(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function Ha(a){this.a=a||v.document||document}function Na(a){var b=a.a;a=!F&&"CSS1Compat"==b.compatMode?b.documentElement:b.body;b=b.parentWindow||b.defaultView;return new I(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)};function Oa(a,b,c){if(y(b))Pa(a,c,b);else{a=fa(Pa,a);for(var d in b)a.call(l,b[d],d,b)}}
function Pa(a,b,c){var d;a:if(d=String(c).replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()}),a.style[d]===l){var e=F?"Webkit":E?"Moz":D?"ms":C?"O":q,f=y(l)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";c=c.replace(RegExp("(^"+(f?"|["+f+"]+":"")+")([a-z])","g"),function(a,b,c){return b+c.toUpperCase()});e=e+c;if(a.style[e]!==l){d=e;break a}}d&&(a.style[d]=b)}
function Qa(a,b){var c=Ia(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,q))?c[b]||c.getPropertyValue(b)||"":""}function L(a,b){return Qa(a,b)||(a.currentStyle?a.currentStyle[b]:q)||a.style&&a.style[b]}function Ra(a){var b=a.getBoundingClientRect();D&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Sa(a){if(D&&!(D&&8<=xa))return a.offsetParent;var b=Ia(a),c=L(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=L(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return q}
function Ta(a){var b=new I;if(1==a.nodeType){if(a.getBoundingClientRect){var c=Ra(a);b.x=c.left;b.y=c.top}else{c=Na(Ga(a));var d,e=Ia(a),f=L(a,"position"),g=E&&e.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==f&&(d=e.getBoxObjectFor(a))&&(0>d.screenX||0>d.screenY),h=new I(0,0),j;d=e?Ia(e):document;if(j=D)if(j=!(D&&9<=xa))j="CSS1Compat"!=Ga(d).a.compatMode;j=j?d.body:d.documentElement;if(a!=j)if(a.getBoundingClientRect)d=Ra(a),e=Na(Ga(e)),h.x=d.left+e.x,h.y=d.top+e.y;else if(e.getBoxObjectFor&&
!g)d=e.getBoxObjectFor(a),e=e.getBoxObjectFor(j),h.x=d.screenX-e.screenX,h.y=d.screenY-e.screenY;else{g=a;do{h.x+=g.offsetLeft;h.y+=g.offsetTop;g!=a&&(h.x+=g.clientLeft||0,h.y+=g.clientTop||0);if(F&&"fixed"==L(g,"position")){h.x+=e.body.scrollLeft;h.y+=e.body.scrollTop;break}g=g.offsetParent}while(g&&g!=a);if(C||F&&"absolute"==f)h.y-=e.body.offsetTop;for(g=a;(g=Sa(g))&&g!=e.body&&g!=j;)if(h.x-=g.scrollLeft,!C||"TR"!=g.tagName)h.y-=g.scrollTop}b.x=h.x-c.x;b.y=h.y-c.y}if(E&&!G(12)){var m;D?m="-ms-transform":
F?m="-webkit-transform":C?m="-o-transform":E&&(m="-moz-transform");var k;m&&(k=L(a,m));k||(k=L(a,"transform"));k?(a=k.match(Ua),a=!a?new I(0,0):new I(parseFloat(a[1]),parseFloat(a[2]))):a=new I(0,0);b=new I(b.x+a.x,b.y+a.y)}}else m="function"==w(a.r),k=a,a.targetTouches?k=a.targetTouches[0]:m&&a.g.targetTouches&&(k=a.g.targetTouches[0]),b.x=k.clientX,b.y=k.clientY;return b}function M(a,b){var c=a.style,d=b;"number"==typeof d&&(d=Math.round(d)+"px");c.width=d}
function N(a){if("none"!=L(a,"display"))return Va(a);var b=a.style,c=b.display,d=b.visibility,e=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=Va(a);b.display=c;b.position=e;b.visibility=d;return a}function Va(a){var b=a.offsetWidth,c=a.offsetHeight,d=F&&!b&&!c;return(b===l||d)&&a.getBoundingClientRect?(a=Ra(a),new K(a.right-a.left,a.bottom-a.top)):new K(b,c)}
function Wa(a,b){var c=a.currentStyle?a.currentStyle[b]:q,d;if(c)if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var e=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=e;d=c}else d=0;return d}var Ua=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;function Xa(){0!=Ya&&z(this)}var Ya=0;function O(a,b){this.type=a;this.a=this.target=b}O.prototype.b=r;O.prototype.i=p;O.prototype.k=function(){this.i=r};var Za=0;function $a(){}$a.prototype.key=0;$a.prototype.m=r;$a.prototype.q=r;$a.prototype.handleEvent=function(a){return this.a?this.j.call(this.z||this.src,a):this.j.handleEvent.call(this.j,a)};var ab=!D||D&&9<=xa,bb=D&&!G("9");!F||G("528");E&&G("1.9b")||D&&G("8")||C&&G("9.5")||F&&G("528");E&&!G("8")||D&&G("9");function cb(a){cb[" "](a);return a}cb[" "]=function(){};function P(a,b){a&&db(this,a,b)}ga(P,O);P.prototype.target=q;P.prototype.clientX=0;P.prototype.clientY=0;P.prototype.g=q;function db(a,b,c){var d=a.type=b.type;O.call(a,d);a.target=b.target||b.srcElement;a.a=c;if((c=b.relatedTarget)&&E)try{cb(c.nodeName)}catch(e){}a.clientX=b.clientX!==l?b.clientX:b.pageX;a.clientY=b.clientY!==l?b.clientY:b.pageY;a.g=b;b.defaultPrevented&&a.k();delete a.b}
P.prototype.k=function(){P.T.k.call(this);var a=this.g;if(a.preventDefault)a.preventDefault();else if(a.returnValue=r,bb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};P.prototype.r=function(){return this.g};var eb={},Q={},R={},S={};function fb(a,b,c,d,e){if("array"==w(b))for(var f=0;f<b.length;f++)fb(a,b[f],c,d,e);else a=gb(a,b,c,r,d,e),eb[a.key]=a}
function gb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");e=!!e;var g=Q;b in g||(g[b]={f:0,c:0});g=g[b];e in g||(g[e]={f:0,c:0},g.f++);var g=g[e],h=z(a),j;g.c++;if(g[h]){j=g[h];for(var m=0;m<j.length;m++)if(g=j[m],g.j==c&&g.z==f){if(g.m)break;d||(j[m].q=r);return j[m]}}else j=g[h]=[],g.f++;var k=hb,t=ab?function(a){return k.call(t.src,t.j,a)}:function(a){a=k.call(t.src,t.j,a);if(!a)return a},m=t,n=g=new $a;if("function"==w(c))n.a=p;else if(c&&c.handleEvent&&"function"==w(c.handleEvent))n.a=
r;else throw Error("Invalid listener argument");n.j=c;n.b=m;n.src=a;n.type=b;n.capture=!!e;n.z=f;n.q=r;n.key=++Za;n.m=r;g.q=d;m.src=a;m.j=g;j.push(g);R[h]||(R[h]=[]);R[h].push(g);a.addEventListener?(a==v||!a.B)&&a.addEventListener(b,m,e):a.attachEvent(b in S?S[b]:S[b]="on"+b,m);return g}function ib(a,b,c,d,e){if("array"==w(b))for(var f=0;f<b.length;f++)ib(a,b[f],c,d,e);else a=gb(a,b,c,p,d,e),eb[a.key]=a}
function kb(a,b,c,d,e){if("array"==w(b))for(var f=0;f<b.length;f++)kb(a,b[f],c,d,e);else{d=!!d;a:{f=Q;if(b in f&&(f=f[b],d in f&&(f=f[d],a=z(a),f[a]))){a=f[a];break a}a=q}if(a)for(f=0;f<a.length;f++)if(a[f].j==c&&a[f].capture==d&&a[f].z==e){lb(a[f].key);break}}}
function lb(a){var b=eb[a];if(b&&!b.m){var c=b.src,d=b.type,e=b.b,f=b.capture;c.removeEventListener?(c==v||!c.B)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in S?S[d]:S[d]="on"+d,e);c=z(c);if(R[c]){var e=R[c],g=Ba(e,b);0<=g&&Aa.splice.call(e,g,1);0==e.length&&delete R[c]}b.m=p;if(b=Q[d][f][c])b.K=p,mb(d,f,c,b);delete eb[a]}}
function mb(a,b,c,d){if(!d.s&&d.K){for(var e=0,f=0;e<d.length;e++)d[e].m?d[e].b.src=q:(e!=f&&(d[f]=d[e]),f++);d.length=f;d.K=r;0==f&&(delete Q[a][b][c],Q[a][b].f--,0==Q[a][b].f&&(delete Q[a][b],Q[a].f--),0==Q[a].f&&delete Q[a])}}function nb(a,b,c,d,e){var f=1;b=z(b);if(a[b]){var g=--a.c,h=a[b];h.s?h.s++:h.s=1;try{for(var j=h.length,m=0;m<j;m++){var k=h[m];k&&!k.m&&(f&=ob(k,e)!==r)}}finally{a.c=Math.max(g,a.c),h.s--,mb(c,d,b,h)}}return Boolean(f)}
function ob(a,b){a.q&&lb(a.key);return a.handleEvent(b)}
function hb(a,b){if(a.m)return p;var c=a.type,d=Q;if(!(c in d))return p;var d=d[c],e,f;if(!ab){var g;if(!(g=b))a:{g=["window","event"];for(var h=v;e=g.shift();)if(h[e]!=q)h=h[e];else{g=q;break a}g=h}e=g;g=p in d;h=r in d;if(g){if(0>e.keyCode||e.returnValue!=l)return p;a:{var j=r;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(m){j=p}if(j||e.returnValue==l)e.returnValue=p}}j=new P;db(j,e,this);e=p;try{if(g){for(var k=[],t=j.a;t;t=t.parentNode)k.push(t);f=d[p];f.c=f.f;for(var n=k.length-1;!j.b&&0<=n&&
f.c;n--)j.a=k[n],e&=nb(f,k[n],c,p,j);if(h){f=d[r];f.c=f.f;for(n=0;!j.b&&n<k.length&&f.c;n++)j.a=k[n],e&=nb(f,k[n],c,r,j)}}else e=ob(a,j)}finally{k&&(k.length=0)}return e}c=new P(b,this);return e=ob(a,c)};function pb(){}pb.a=function(){pb.b||(pb.b=new pb)};pb.a();function qb(){Xa.call(this)}ga(qb,Xa);qb.prototype.B=p;qb.prototype.addEventListener=function(a,b,c,d){fb(this,a,b,c,d)};qb.prototype.removeEventListener=function(a,b,c,d){kb(this,a,b,c,d)};function rb(a){console.log(a)};function T(a){Xa.call(this);this.b=a||window;fb(this.b,"resize",this.N,r,this);this.e=Ka(this.b||window);window.setInterval(ea(this.r,this),sb)}ga(T,qb);var sb=100;T.prototype.b=q;T.prototype.e=q;T.prototype.N=function(){this.r()};
T.prototype.r=function(){var a=Ka(this.b||window);if(!(a==this.e||(!a||!this.e?0:a.width==this.e.width&&a.height==this.e.height))){this.e=a;var a="resize",b=a.type||a,c=Q;if(b in c){if(y(a))a=new O(a,this);else if(a instanceof O)a.target=a.target||this;else{var d=a,a=new O(b,this);za(a,d)}var d=1,e,c=c[b],b=p in c,f;if(b){e=[];for(f=this;f;f=q)e.push(f);f=c[p];f.c=f.f;for(var g=e.length-1;!a.b&&0<=g&&f.c;g--)a.a=e[g],d&=nb(f,e[g],a.type,p,a)&&a.i!=r}if(r in c)if(f=c[r],f.c=f.f,b)for(g=0;!a.b&&g<e.length&&
f.c;g++)a.a=e[g],d&=nb(f,e[g],a.type,r,a)&&a.i!=r;else for(e=this;!a.b&&e&&f.c;e=q)a.a=e,d&=nb(f,e,a.type,r,a)&&a.i!=r}}};var U;U=function(){return p};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

The "New" BSD License:

Copyright (c) 2005-2009, The Dojo Foundation
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
function tb(a,b){var c=b||[];a&&c.push(a);return c}var ub=F&&"BackCompat"==document.compatMode,vb=document.firstChild.children?"children":"childNodes",V=r;
function wb(a){function b(){0<=m&&(s.id=c(m,u).replace(/\\/g,""),m=-1);if(0<=k){var a=k==u?q:c(k,u);0>">~+".indexOf(a)?s.d=a:s.u=a;k=-1}0<=j&&(s.h.push(c(j+1,u).replace(/\\/g,"")),j=-1)}function c(b,c){return ha(a.slice(b,c))}a=0<=">~+".indexOf(a.slice(-1))?a+" * ":a+" ";for(var d=[],e=-1,f=-1,g=-1,h=-1,j=-1,m=-1,k=-1,t="",n="",jb,u=0,Pb=a.length,s=q,x=q;t=n,n=a.charAt(u),u<Pb;u++)if("\\"!=t)if(s||(jb=u,s={o:q,l:[],p:[],h:[],d:q,u:q,id:q,w:function(){return V?this.R:this.d}},k=u),0<=e)if("]"==n){x.v?
x.A=c(g||e+1,u):x.v=c(e+1,u);if((e=x.A)&&('"'==e.charAt(0)||"'"==e.charAt(0)))x.A=e.slice(1,-1);s.p.push(x);x=q;e=g=-1}else"="==n&&(g=0<="|~^$*".indexOf(t)?t:"",x.type=g+n,x.v=c(e+1,u-g.length),g=u+1);else 0<=f?")"==n&&(0<=h&&(x.value=c(f+1,u)),h=f=-1):"#"==n?(b(),m=u+1):"."==n?(b(),j=u):":"==n?(b(),h=u):"["==n?(b(),e=u,x={}):"("==n?(0<=h&&(x={name:c(h+1,u),value:q},s.l.push(x)),f=u):" "==n&&t!=n&&(b(),0<=h&&s.l.push({name:c(h+1,u)}),s.J=s.l.length||s.p.length||s.h.length,s.V=s.o=c(jb,u),s.R=s.d=
s.u?q:s.d||"*",s.d&&(s.d=s.d.toUpperCase()),d.length&&d[d.length-1].u&&(s.G=d.pop(),s.o=s.G.o+" "+s.o),d.push(s),s=q);return d}function W(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function xb(a){return 1==a.nodeType}function X(a,b){return!a?"":"class"==b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(V?a.getAttribute(b):a.getAttribute(b,2))||""}
var yb={"*=":function(a,b){return function(c){return 0<=X(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==X(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+X(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+X(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+X(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return X(c,a)==b}}},zb="undefined"==
typeof document.firstChild.nextElementSibling,Ab=!zb?"nextElementSibling":"nextSibling",Bb=!zb?"previousElementSibling":"previousSibling",Cb=zb?xb:U;function Db(a){for(;a=a[Bb];)if(Cb(a))return r;return p}function Eb(a){for(;a=a[Ab];)if(Cb(a))return r;return p}function Fb(a){var b=a.parentNode,c=0,d=b[vb],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Ab])Cb(b)&&(b._i=++c,a===b&&(e=c));return e}
function Gb(a){return!(Fb(a)%2)}function Hb(a){return Fb(a)%2}
var Ib={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return Db},"last-child":function(){return Eb},"only-child":function(){return function(a){return!Db(a)||!Eb(a)?r:p}},empty:function(){return function(a){var b=a.childNodes;for(a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;if(1===c||3==c)return r}return p}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},
not:function(a,b){var c=wb(b)[0],d={n:1};"*"!=c.d&&(d.d=1);c.h.length||(d.h=1);var e=Y(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return Hb;if("even"==b)return Gb;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<e&&(e>=d&&(f=e-e%d),e=e%d):0>d&&(d*=-1,0<e&&(g=e,e=e%d));if(0<d)return function(a){a=Fb(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var h=parseInt(b,10);return function(a){return Fb(a)==
h}}},Jb=D?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return V?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}};
function Y(a,b){if(!a)return U;b=b||{};var c=q;b.n||(c=W(c,xb));b.d||"*"!=a.d&&(c=W(c,function(b){return b&&b.tagName==a.w()}));b.h||H(a.h,function(a,b){var f=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=W(c,function(a){return f.test(a.className)});c.count=b});b.l||H(a.l,function(a){var b=a.name;Ib[b]&&(c=W(c,Ib[b](b,a.value)))});b.p||H(a.p,function(a){var b,f=a.v;a.type&&yb[a.type]?b=yb[a.type](f,a.A):f.length&&(b=Jb(f));b&&(c=W(c,b))});b.id||a.id&&(c=W(c,function(b){return!!b&&b.id==a.id}));c||"default"in
b||(c=U);return c}var Kb={};
function Lb(a){var b=Kb[a.o];if(b)return b;var c=a.G,c=c?c.u:"",d=Y(a,{n:1}),e="*"==a.d,f=document.getElementsByClassName;if(c)if(f={n:1},e&&(f.d=1),d=Y(a,f),"+"==c)var g=d,b=function(a,b,c){for(;a=a[Ab];)if(!zb||xb(a)){(!c||Mb(a,c))&&g(a)&&b.push(a);break}return b};else if("~"==c)var h=d,b=function(a,b,c){for(a=a[Ab];a;){if(Cb(a)){if(c&&!Mb(a,c))break;h(a)&&b.push(a)}a=a[Ab]}return b};else{if(">"==c)var j=d,j=j||U,b=function(a,b,c){for(var d=0,e=a[vb];a=e[d++];)Cb(a)&&((!c||Mb(a,c))&&j(a,d))&&b.push(a);
return b}}else if(a.id)d=!a.J&&e?U:Y(a,{n:1,id:1}),b=function(b,c){var e;e=Ga(b);var f=a.id;if(f=(e=y(f)?e.a.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&f!=b;)f=f.parentNode;f=!!f}if(f)return tb(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(String(f))&&a.h.length&&!ub)var d=Y(a,{n:1,h:1,id:1}),m=a.h.join(" "),b=function(a,b){for(var c=tb(0,b),e,f=0,g=a.getElementsByClassName(m);e=g[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.J?b=function(b,c){for(var d=tb(0,c),e,f=
0,g=b.getElementsByTagName(a.w());e=g[f++];)d.push(e);return d}:(d=Y(a,{n:1,d:1,id:1}),b=function(b,c){for(var e=tb(0,c),f,g=0,h=b.getElementsByTagName(a.w());f=h[g++];)d(f,b)&&e.push(f);return e});return Kb[a.o]=b}var Nb={},Ob={};
function Qb(a){var b=wb(ha(a));if(1==b.length){var c=Lb(b[0]);return function(a){if(a=c(a,[]))a.t=p;return a}}return function(a){a=tb(a);for(var c,f,g=b.length,h,j,m=0;m<g;m++){j=[];c=b[m];f=a.length-1;0<f&&(h={},j.t=p);f=Lb(c);for(var k=0;c=a[k];k++)f(c,j,h);if(!j.length)break;a=j}return j}}var Rb=!!document.querySelectorAll&&(!F||G("526"));
function Sb(a,b){if(Rb){var c=Ob[a];if(c&&!b)return c}if(c=Nb[a])return c;var c=a.charAt(0),d=-1==a.indexOf(" ");0<=a.indexOf("#")&&d&&(b=p);if(Rb&&!b&&-1==">~+".indexOf(c)&&(!D||-1==a.indexOf(":"))&&!(ub&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var e=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return Ob[a]=function(b){try{if(!(9==b.nodeType||d))throw"";var c=b.querySelectorAll(e);D?c.L=p:c.t=p;return c}catch(f){return Sb(a,p)(b)}}}var f=a.split(/\s*,\s*/);return Nb[a]=
2>f.length?Qb(a):function(a){for(var b=0,c=[],d;d=f[b++];)c=c.concat(Qb(d)(a));return c}}var Z=0,Tb=D?function(a){return V?a.getAttribute("_uid")||a.setAttribute("_uid",++Z)||Z:a.uniqueID}:function(a){return a._uid||(a._uid=++Z)};function Mb(a,b){if(!b)return 1;var c=Tb(a);return!b[c]?b[c]=1:0}
function Ub(a){if(a&&a.t)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;Z++;if(D&&V){var c=Z+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(D&&a.L)try{for(d=1;e=a[d];d++)xb(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=Z);for(d=1;e=a[d];d++)a[d]._zipIdx!=Z&&b.push(e),e._zipIdx=Z}return b}
function Vb(a,b){if(!a)return[];if(a.constructor==Array)return a;if(!y(a))return[a];if(y(b)&&(b=Ja(b),!b))return[];b=b||document;var c=b.ownerDocument||b.documentElement;V=b.contentType&&"application/xml"==b.contentType||C&&(b.doctype||"[object XMLDocument]"==c.toString())||!!c&&(D?c.xml:b.xmlVersion||c.xmlVersion);return(c=Sb(a)(b))&&c.t?c:Ub(c)}Vb.l=Ib;A("goog.dom.query",Vb);A("goog.dom.query.pseudos",Vb.l);function $(a,b,c){T.call(this);this.k=new K(b,0);this.O=new K(c,0);b=this.log=rb;c=this.i=Ja;this.g=c(a);this.C=this.e?this.e.a():q;this.D=this.a=N(this.g);a=Vb("#"+a+"> ."+Wb);var d;b("lenght:"+a.length);this.F=[];this.I=[];this.S=[];this.H=[];c=[];for(var e=0;e<a.length;e++){b("asdas");var f='<div class="'+Fa+'" style="float:left;min-height:1em; width:0px"></div>',g=document;d=g.createElement("div");D?(d.innerHTML="<br>"+f,d.removeChild(d.firstChild)):d.innerHTML=f;if(1==d.childNodes.length)d=d.removeChild(d.firstChild);
else{for(f=g.createDocumentFragment();d.firstChild;)f.appendChild(d.firstChild);d=f}f=a[e];f.insertBefore(d,f.childNodes[0]||q);Ca(c,d)}}ga($,T);var Wb="q",Fa="p";$.prototype.P=function(a){Ca(this.F,this.i(a))};$.prototype.Q=function(a){Ca(this.H,this.i(a))};
$.prototype.refresh=function(){var a=this.a,b=this.D=a.a(),c=this.C=this.e?this.e.a():q;c.width!=a.width&&(this.log("currentViewportSize.width:"+c.width),c.width>this.k.width&&c.width<this.O.width?(a.width=c.width,M(this.g,a.width),this.log("currentContainerSize.width:"+a.width),this.log("lastContainerSize.width:"+b.width),this.log("halfDifferenceWidth:"+(a.width-b.width)/2)):c.width<=this.k.width&&(a.width=this.k.width,M(this.g,a.width)),this.a=a);H(this.F,function(a){for(var b=0,c=La(a);c!=q&&Ea(c);)b=
b+N(c).width,M(c,0),c=La(c);b=0;for(c=a.nextElementSibling!=l?a.nextElementSibling:Ma(a.nextSibling,p);c!=q&&Ea(c);)b=b+N(c).width,M(c,0),c=c.nextElementSibling!=l?c.nextElementSibling:Ma(c.nextSibling,p);b=N(a).width;if(c==q){var c=Ta(this.g),g=Ta(a);this.log("coord: "+(new I(c.x-g.x,c.y-g.y)).x)}M(a,Math.floor(b*(this.a.width/this.D.width)+2E-15))},this);H(this.I,function(a){for(var b=0,c=La(a);c!=q&&Ea(c);)b=b+N(c).width,M(c,0),c=La(c);this.log("el");this.log(a);Oa(a,"margin-left",(this.a.width-
N(a).width)/2+"px")},this);H(this.H,function(a){var b=new I(a.offsetLeft,a.offsetTop);this.log("el");this.log(a);var b=this.C.height-b.y-1-N(a).height,c;if(D){c=Wa(a,"marginLeft");var g=Wa(a,"marginRight"),h=Wa(a,"marginTop"),j=Wa(a,"marginBottom");c=new J(h,g,j,c)}else c=Qa(a,"marginLeft"),g=Qa(a,"marginRight"),h=Qa(a,"marginTop"),j=Qa(a,"marginBottom"),c=new J(parseFloat(h),parseFloat(g),parseFloat(j),parseFloat(c));b=b+c.top;0>b&&(b=0);this.log("margiTop:"+b);Oa(a,"margin-top",b+"px")},this);H(this.S,
function(a){this.log("el");this.log(a);var b=this.a.width-N(a).width;0>b&&(b=0);this.log("margiLeft:"+b);Oa(a,"margin-left",b+"px")},this);ib(this,"resize",function(){this.refresh();this.log("Viewport size changed to "+(this.e?this.e.a():q))},r,this)};A("ax.ui.Scaffolding",$);A("ax.ui.Scaffolding.prototype.subscribeToFillMaxWidth",$.prototype.P);A("ax.ui.Scaffolding.prototype.subscribeToRepositionToBottomScreen",$.prototype.Q);A("ax.ui.Scaffolding.prototype.refresh",$.prototype.refresh);A("axmain.about.About",function(a){var b=new $("continerId",960,2E3);this.a=a;this.a.U=a.initState;this.a.M=a.initData;this.a.M.W=a.initData.resultItemList;this.a.path=a.path;this.a.path.root=a.path.root;Ca(b.I,b.i("spanTextId"));b.refresh()});
