// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/mycompany/helloworld/hello.proto

/**
 * @fileoverview Generated Protocol Buffer code for file com/mycompany/helloworld/hello.proto.
 */

goog.provide('pbdesc.com.mycompany.helloworld.HelloMsg');

goog.require('goog.proto2.Message');



/**
 * Message HelloMsg.
 * @constructor
 * @extends {goog.proto2.Message}
 */
pbdesc.com.mycompany.helloworld.HelloMsg = function() {
  goog.proto2.Message.apply(this);
};
goog.inherits(pbdesc.com.mycompany.helloworld.HelloMsg, goog.proto2.Message);


/**
 * Overrides {@link goog.proto2.Message#clone} to specify its exact return type.
 * @return {!pbdesc.com.mycompany.helloworld.HelloMsg} The cloned message.
 * @override
 */
pbdesc.com.mycompany.helloworld.HelloMsg.prototype.clone;


/**
 * Gets the value of the text field.
 * @return {?string} The value.
 */
pbdesc.com.mycompany.helloworld.HelloMsg.prototype.getText = function() {
  return /** @type {?string} */ (this.get$Value(1));
};


/**
 * Gets the value of the text field or the default value if not set.
 * @return {string} The value.
 */
pbdesc.com.mycompany.helloworld.HelloMsg.prototype.getTextOrDefault = function() {
  return /** @type {string} */ (this.get$ValueOrDefault(1));
};


/**
 * Sets the value of the text field.
 * @param {string} value The value.
 */
pbdesc.com.mycompany.helloworld.HelloMsg.prototype.setText = function(value) {
  this.set$Value(1, value);
};


/**
 * @return {boolean} Whether the text field has a value.
 */
pbdesc.com.mycompany.helloworld.HelloMsg.prototype.hasText = function() {
  return this.has$Value(1);
};


/**
 * @return {number} The number of values in the text field.
 */
pbdesc.com.mycompany.helloworld.HelloMsg.prototype.textCount = function() {
  return this.count$Values(1);
};


/**
 * Clears the values in the text field.
 */
pbdesc.com.mycompany.helloworld.HelloMsg.prototype.clearText = function() {
  this.clear$Field(1);
};



goog.proto2.Message.set$Metadata(pbdesc.com.mycompany.helloworld.HelloMsg, {
  0: {
    name: 'HelloMsg',
    fullName: 'HelloMsg'
  },
  1: {
    name: 'text',
    fieldType: goog.proto2.Message.FieldType.STRING,
    type: String
  }
});
